version: '3.0'

services:
    dql-server:
      container_name: dql-server
      ports:
        - 5000:5000
      build:
        context: .
        args:
          _port: 5000
          _host: 0.0.0.0
        # _firebase_port: 
          _firebase_host: https://www.googleapis.com
          _api_key: FIREBASE_API_KEY_GOES_HERE
          _debug: 'dev'
      volumes:
        - /home/david/dql:/app